# Generated by Django 6.1 on 2026-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery_engine', '0003_contentitem_external_id_alter_contentitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('LIKE', 'Like'), ('SAVE', 'Save for Later'), ('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote')], default='CLICK', max_length=10),
        ),
    ]
