# Generated by Django 6.1 on 2026-08-29 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery_engine', '0004_contentitem_downvotes_contentitem_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
    ]
