# Generated by Django 5.2.17 on 2026-09-29 20:10

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('discovery_engine', '0005_contentitem_ai_summary_contentitem_embedding'),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterField(
            model_name='contentitem',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
